#!/bin/sh
if [ -c "/dev/mapper/control" ]; then
    if eval /sbin/cryptsetup luksOpen \`cat /.cryptdev\` \`cat /.cryptname\` \`cat /.cryptargs\` ; then
        echo > /.done
        killall cryptsetup
        killall --quiet plymouth
    fi
else
    echo "encryption bootup not succeeded. please wait!"
fi
