#!/bin/sh
if [ -c "/dev/mapper/control" ]; then
    if eval cryptsetup open --type luks \`cat /.cryptdev\` \`cat /.cryptname\` \`cat /.cryptargs\` ; then
        echo > /.done
        killall cryptsetup
    fi
else
    echo "encryption bootup not succeeded. please wait!"
fi
